[java_test(
    name = "UtilsTest_%d" % i,
    srcs = ["src/test/java/com/harness/utils/UtilsTest_%d.java" % i],
    test_class = "com.harness.utils.UtilsTest_%d" % i,
    deps = [
        "@maven//:junit_junit",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:joda_time_joda_time",
    ],
) for i in range(1, 11)]
